"""empty message

Revision ID: 12d7c59dce1d
Revises: 37e24f7a56c6
Create Date: 2014-11-18 20:50:54.293847

"""

# revision identifiers, used by Alembic.
revision = '12d7c59dce1d'
down_revision = '37e24f7a56c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('scenario', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'scenario')
    ### end Alembic commands ###
