"""empty message

Revision ID: 20556161751
Revises: d19beccb094
Create Date: 2014-11-18 22:31:05.254711

"""

# revision identifiers, used by Alembic.
revision = '20556161751'
down_revision = 'd19beccb094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
