"""empty message

Revision ID: 37e24f7a56c6
Revises: None
Create Date: 2014-11-15 11:08:01.572959

"""

# revision identifiers, used by Alembic.
revision = '37e24f7a56c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('run_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
