"""empty message

Revision ID: 387c07388404
Revises: 12d7c59dce1d
Create Date: 2014-11-18 22:04:16.656481

"""

# revision identifiers, used by Alembic.
revision = '387c07388404'
down_revision = '12d7c59dce1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'status')
    ### end Alembic commands ###
