"""empty message

Revision ID: 3bba19a08ca0
Revises: 3d174022aaa4
Create Date: 2014-11-15 10:05:09.904943

"""

# revision identifiers, used by Alembic.
revision = '3bba19a08ca0'
down_revision = '3d174022aaa4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
