"""empty message

Revision ID: 3d174022aaa4
Revises: None
Create Date: 2014-11-15 10:02:29.874573

"""

# revision identifiers, used by Alembic.
revision = '3d174022aaa4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
