"""empty message

Revision ID: cb99ca79479
Revises: 7511869c0aa
Create Date: 2014-11-21 16:32:37.744311

"""

# revision identifiers, used by Alembic.
revision = 'cb99ca79479'
down_revision = '7511869c0aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('scenario_check_sum', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'scenario_check_sum')
    ### end Alembic commands ###
