"""empty message

Revision ID: d19beccb094
Revises: 387c07388404
Create Date: 2014-11-18 22:10:21.217623

"""

# revision identifiers, used by Alembic.
revision = 'd19beccb094'
down_revision = '387c07388404'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('run_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'run_id')
    ### end Alembic commands ###
